[package]
name = "quizz-core"
version = "0.1.0"
edition = "2024"

[dependencies]
quizz-common = { path = "../common" }
thiserror = "2.0.11"
regex = "1.10.2"
async-trait = "0.1.88"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
