[workspace]
resolver = "2"
members = [
    # Subdominio basico
    "bounded-ctx/core",

    # Subdominios de soporte
    "bounded-ctx/usermgm",
    "bounded-ctx/auth",

    # API backend
    "cmd/api",
]
