services:
#   quizz-api:
#     container_name: quizz-api
#     command: sleep infinity
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     networks:
#       - frontend
#       - backend
#     environment:
#       - DATABASE_URL=postgres://quizz:quizz@postgres:5432/quizz

#   quizz-ui:
#     container_name: quizz-ui
#     command: sleep infinity
#     build:
#       context: ./web
#       dockerfile: Dockerfile
#     ports:
#       - "3333:3333"
#     networks:
#       - frontend

  postgres:
    container_name: quizz-postgres
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quizz
      POSTGRES_PASSWORD: quizz
      POSTGRES_DB: quizz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend:
