[package]
name = "quizz-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
uuid = { version = "1.15.1", features = ["v7"] }
thiserror = "2.0.11"
